### ISSUE TITLE
Invalid icon warning

### ISSUE THREAD

**Issue by ghost-101** [Lykrast/Glassential#2]
```
[main/ERROR]: Invalid icon for mod Glassential
java.lang.IllegalStateException: Must be square icon
	at org.apache.commons.lang3.Validate.validState(Validate.java:829) ~[commons-lang3-3.5.jar:3.5]
	at io.github.prospector.modmenu.gui.ModListEntry.createIcon(ModListEntry.java:80) ~[modmenu-1.6.3+build.101.jar:?]
	at io.github.prospector.modmenu.gui.ModListEntry.<init>(ModListEntry.java:40) ~[modmenu-1.6.3+build.101.jar:?]
	at io.github.prospector.modmenu.gui.entries.IndependentEntry.<init>(IndependentEntry.java:10) ~[modmenu-1.6.3+build.101.jar:?]
	at io.github.prospector.modmenu.gui.ModListWidget.filter(ModListWidget.java:119) ~[modmenu-1.6.3+build.101.jar:?]
	at io.github.prospector.modmenu.gui.ModListScreen.lambda$init$1(ModListScreen.java:80) ~[modmenu-1.6.3+build.101.jar:?]
	at net.minecraft.class_342.method_1874(class_342.java:153) ~[intermediary-minecraft-1.14.3-client.jar:?]
	at net.minecraft.class_342.method_1883(class_342.java:263) ~[intermediary-minecraft-1.14.3-client.jar:?]
	at net.minecraft.class_342.method_1855(class_342.java:253) ~[intermediary-minecraft-1.14.3-client.jar:?]
	at net.minecraft.class_342.method_1878(class_342.java:208) ~[intermediary-minecraft-1.14.3-client.jar:?]
	at net.minecraft.class_342.method_16873(class_342.java:162) ~[intermediary-minecraft-1.14.3-client.jar:?]
	at net.minecraft.class_342.keyPressed(class_342.java:325) ~[intermediary-minecraft-1.14.3-client.jar:?]
	at net.minecraft.class_4069.keyPressed(class_4069.java:64) ~[intermediary-minecraft-1.14.3-client.jar:?]
	at net.minecraft.class_437.keyPressed(class_437.java:95) ~[intermediary-minecraft-1.14.3-client.jar:?]
	at io.github.prospector.modmenu.gui.ModListScreen.keyPressed(ModListScreen.java:169) ~[modmenu-1.6.3+build.101.jar:?]
	at net.minecraft.class_309.lambda$onKeyEvent$4(class_309.java:446) ~[intermediary-minecraft-1.14.3-client.jar:?]
	at net.minecraft.class_437.wrapScreenError(class_437.java:441) ~[intermediary-minecraft-1.14.3-client.jar:?]
	at net.minecraft.class_309.method_1466(class_309.java:413) ~[intermediary-minecraft-1.14.3-client.jar:?]
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:37) [lwjgl-glfw-3.2.2.jar:build 10]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10]
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174) [lwjgl-glfw-3.2.2.jar:build 10]
	at net.minecraft.class_1041.method_15996(class_1041.java:422) [intermediary-minecraft-1.14.3-client.jar:?]
	at net.minecraft.class_310.method_15994(class_310.java:1027) [intermediary-minecraft-1.14.3-client.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:976) [intermediary-minecraft-1.14.3-client.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:411) [intermediary-minecraft-1.14.3-client.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:154) [intermediary-minecraft-1.14.3-client.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:170) [fabric-loader-0.4.8+build.155.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:129) [fabric-loader-0.4.8+build.155.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26) [fabric-loader-0.4.8+build.155.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
```

**Comment by Lykrast** [comment]
This is the Forge repo, the Fabric one is over here : https://github.com/Lykrast/Glassential-Fabric
